### ISSUE TITLE
Feature request: Ignore specified files/folders

### ISSUE THREAD

**Issue by tello2004** [dlbeswick/gio-sync#1]
I'm currently using this tool to backup certain folders in my laptop: code projects, most of them Node.js-based, and personal documents. And in both cases I'd love to be able to ignore certain things from the syncing process, like `.git` and `node_modules` folders.

This feature could be implemented behind of a `--ignore` flag or a `.gio-sync-ignore` file with a list of paths, or both options.

**Comment by dlbeswick** [comment]
Hello there! Nice to know that you're getting some good use from the project.

This feature makes perfect sense, but I'm curious -- are you just backing up files from disk-to-disk? Is there a reason for your usecase that "rsync" isn't a better choice?

**Comment by nohayproblema** [comment]
Yes! I'm using the Google Drive backend. And I know there's things like rclone and google-drive-ocamlfuse, but it makes more sense for me to use the already built-in GVFS instead of yet another tool that comes with its own set of extra dependencies. It integrates perfectly on my GNOME desktop.

**Comment by dlbeswick** [comment]
I see! Thanks for the detail, that does make sense. I can certainly look at
this for you over the coming weeks. Since I know someone's using it, I'll
have a go at packaging it up in PIP, too.

If you're keen to make the change, of course please feel free to have a go
at a PR, too.

ในวันที่ พฤ. 4 ก.ค. 2024 09:58 Martín Aguilar ***@***.***>
เขียนว่า:

**Comment by dlbeswick** [comment]
Thanks for your patience, @quienn . I've added the feature to the master branch, please test it out if you have a moment and let me know how you go.

There are three new options documented in the readme here: https://github.com/dlbeswick/gio-sync?tab=readme-ov-file#ignore-filesexclusions

This code is still under test, please use `--dry-run` to make sure you don't lose any important files!

**Comment by dlbeswick** [comment]
Also available as release here: https://github.com/dlbeswick/gio-sync/releases/tag/rc1.1.0-1

**Comment by nohayproblema** [comment]
Hey dlbeswick, sorry for the wait. It's been a rough run for me these past couple months.

It works! I've been using for quite a while and I can say it has worked great for such a niche use-case! Thanks, and I hope to contribute a couple of other ideas I got later. Sincerely.

**Comment by dlbeswick** [comment]
I totally understand @quienn, that's no problem at all and I appreciate you taking the time to test the feature; that's invaluable. I myself am continuing to try to find some time to package the project properly in PyPI and will let you know when I've done so, for your convenience.

Thank you for your contribution and for using the project!
